Repository NLog/NLog.Web, pull requests merged in 2018-04, with the labels that each got.

#268 NLogBuilder is needed, because DLL autoload doesn't work
  NLog.Web.AspNetCore/AspNetExtensions.cs
  NLog.Web.AspNetCore/NLogBuilder.cs
  examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Program.cs
Labels: bug

#269 Version 4.5.1 (asp.net core)
  CHANGELOG.MD
  NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: build, docs

#272 Removed explicit registration of hidden assemblies for callsite handling
  NLog.Web.AspNetCore/AspNetExtensions.cs
  NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: ASP.NET Core 2, enhancement

#273 Added public method to configure the NLog ServiceLocator
  NLog.Web.AspNetCore/AspNetExtensions.cs
  NLog.Web.AspNetCore/Internal/ServiceLocator.cs
Labels: ASP.NET Core 1, ASP.NET Core 2, feature

#275 ${aspnet-request-ip} handle emtpy Request on HttpContext
  NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs
Labels: ASP.NET 4, bug

#276 Version 4.5.2 - ASP.NET Core
  CHANGELOG.MD
  NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: version

#277 Version 4.5.3 - ASP.NET + Update NLog dependency
  CHANGELOG.MD
  NLog.Web/NLog.Web.csproj
  NLog.Web/packages.NLog.Web.config
  appveyor.yml
Labels: version
