Repository NLog/NLog.Web, pull requests merged in 2019-09, with the labels that each got.

#459 Fixed double logging mixing UseNLog with AddNLog
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: merge when passing, size/XS

#460 Release notes - Version 4.8.5
  CHANGELOG.MD
  NLog.Web.sln
  appveyor.yml
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web/NLog.Web.csproj
Labels: size/S

#461 Release 4.8.5
  .github/ranger.yml
  CHANGELOG.MD
  NLog.Web.sln
  appveyor.yml
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web/NLog.Web.csproj
  tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
  tests/NLog.Web.Tests/NLog.Web.Tests.csproj
Labels: merge when passing, size/M, version

#465 ${aspnet-request-cookie} (without cookienames) will render all cookies
  src/Shared/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetCookieLayoutRendererTests.cs
Labels: ASP.NET 4, ASP.NET Core 1, ASP.NET Core 2, enhancement, size/M

#466 update Microsoft.AspNetCore dependencies
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: ASP.NET Core 1, ASP.NET Core 2, dependencies, size/S

#467 Update MSTest
  tests/NLog.Web.Tests/NLog.Web.Tests.csproj
Labels: dependencies, size/XS, test

#468 Make namespaces in test projects consistent
  NLog.Web.sln.DotSettings
  tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
  tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
  tests/NLog.Web.Tests/DefaultHttpContextAccessorTests.cs
  tests/Shared/FakeHttpContextAccessor.cs
  tests/Shared/LayoutRenderers/AspNetRequestPostedBodyTests.cs
  tests/Shared/LayoutRenderers/AssemblyVersionLayoutRendererTests.cs
  tests/Shared/RegisterCustomLayoutRenderer.cs
  tests/Shared/TestBase.cs
Labels: merge when passing, test

#476 Revert update microsoft.asp net core
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: dependencies, merge when passing, size/XS

#472 AspNetRequestCookieLayoutRenderer - Added support for Exclude
  src/Shared/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestFormLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetCookieLayoutRendererTests.cs
Labels: feature, size/M, squash when passing

#473 Added ASP.NET + ASP.NET Core layout renderer for rendering headers
  src/Shared/LayoutRenderers/AspNetRequestHeadersLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetRequestHeadersLayoutRendererTests.cs
Labels: feature, size/L

#477 Added ${aspnet-response-statuscode} - rendering response status code
  src/Shared/Internal/HttpContextExtensions.cs
  src/Shared/LayoutRenderers/AspNetResponseStatusCodeRenderer.cs
  tests/Shared/LayoutRenderers/AspNetResponseStatusCodeRendererTests.cs
Labels: feature, merge when passing, needs documentation on nlog-project.org/config, needs documentation on wiki, size/L

#478 IHostingEnvironment is obsolete in NetCore3. Instead use ILoggingBuilder.ConfigureNLog
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
Labels: ASP.NET Core 2, enhancement, size/XS

#483 AddNLog-methods for ILoggingBuilder
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
Labels: feature, size/M

#484 Let IHostBuilder AddNLog work correctly with ${configsetting}
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
Labels: ASP.NET Core 1, ASP.NET Core 2, enhancement, size/M

#485 Fixed bug introduced with IServiceCollection.Replace. Instead use TryAddEnumerable
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
Labels: size/S

#487 Fixed: Mixing AddDebug() with a file based NLog configuration no longer works
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
Labels: ASP.NET Core 1, ASP.NET Core 2, size/XS

#488 Release 4.8.6
  CHANGELOG.MD
  appveyor.yml
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: Patch Version, merge when passing, size/S, version

#490 Port 4.8.6 to dev
  CHANGELOG.MD
  appveyor.yml
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: merge when passing, size/S
