Repository NLog/NLog.Web, pull requests merged in 2020-12, with the labels that each got.

#616 Move to PackageIcon and PackageLicenseExpression for NuGet package
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web/NLog.Web.csproj
Labels: build, package, size/S

#611 Update NuGet API key
  appveyor.yml
Labels: build, size/XS, squash when passing

#617 Added ASP.NET Core 5 supported in README
  README.md
Labels: size/XS

#614 ASPNETCORE_ENVIRONMENT takes now precedence over DOTNET_ENVIRONMENT
  src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs
Labels: bug, enhancement, size/XS, squash when passing

#621 Updated example NLog.config to include logging of hosting lifetime messages
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/NLog.config
Labels: docs, example, size/S

#624 Version 4.10
  CHANGELOG.MD
  appveyor.yml
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: size/S, version
