Repository NLog/NLog.Web, pull requests merged in 2020-04, with the labels that each got.

#530 ${aspnet-request-url} Added UseRawTarget option
  src/Shared/LayoutRenderers/AspNetRequestUrlRenderer.cs
  tests/Shared/LayoutRenderers/AspNetRequestUrlRendererTests.cs
Labels: ASP.NET Core 1, ASP.NET Core 2, ASP.NET Core 3, feature, size/M

#546 ${aspnet-request-ip}: make ForwardedForHeader configurable
  src/Shared/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetRequestIpLayoutRendererTests.cs
Labels: size/M

#550 Release 4.9.2
  CHANGELOG.MD
  appveyor.yml
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web/NLog.Web.csproj
  src/Shared/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestUrlRenderer.cs
  tests/NLog.Web.Tests/NLog.Web.Tests.csproj
  tests/Shared/LayoutRenderers/AspNetRequestIpLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestUrlRendererTests.cs
Labels: size/L, version

#553 Various code improvements
  src/Shared/LayoutRenderers/AspNetLayoutMultiValueRendererBase.cs
  src/Shared/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs
  tests/Shared/LayoutRenderers/TestInvolvingAspNetHttpContext.cs
Labels: refactoring, size/L
