Repository NLog/NLog.Web, pull requests merged in 2021-08, with the labels that each got.

#682 Fix import in ASP.NET Core 5 example
  NLog.Web.sln
  examples/ASP.NET Core 5/ASP.NET Core 5 NLog Example/Program.cs
Labels: docs, size/S

#687 Set up CI with Azure Pipelines
  azure-pipelines.yml
Labels: build, size/M

#688 Release 4.14
  CHANGELOG.MD
  appveyor.yml
  build.ps1
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: size/S

#683 Drop support ASP.NET Core 1
  README.md
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
  src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/Shared/Internal/HttpContextExtensions.cs
  src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestPostedBody.cs
  src/Shared/LayoutRenderers/AspNetWebRootPathLayoutRenderer.cs
  src/Shared/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
  tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
  tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
  tests/Shared/TestBase.cs
Labels: size/M

#690 ASP_NET_CORE2 is now the odd one
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
  src/Shared/LayoutRenderers/AspNetRequestPostedBody.cs
Labels: size/M

#691 NLogAspNetCoreOptions - Enable ShutdownOnDispose by default
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
  src/NLog.Web.AspNetCore/NLogAspNetCoreOptions.cs
Labels: enhancement, size/S

#692 Update ASP.NET example project to add NLog.Web extension
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/NLog.config
Labels: size/XS

#693 NLog.Web-package release notes about explicit registration of NLog.Web
  NLog.Web.sln
  README.md
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/NLog.config
  src/NLog.Web/NLog.Web.csproj
Labels: size/M
