Repository NLog/NLog.Web, pull requests merged in 2021-12, with the labels that each got.

#738 Update NuGet API key
  appveyor.yml
Labels: build, size/XS

#735 Changed format Culture to InvariantCulture to match default NLog Culture
  src/NLog.Web/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestDurationLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
  tests/NLog.Web.Tests/LayoutRenderers/AspNetApplicationValueLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetItemValueLayoutRendererTests.cs
Labels: enhancement, breaking change, size/M

#741 Changed from Convert.ToString to IValueFormatter to be like NLog default
  src/NLog.Web/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs
  src/Shared/Internal/StringBuilderExtensions.cs
  src/Shared/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
Labels: enhancement, size/M

#740 Added Layout renderer for ASP.NET Request route parameters
  src/Shared/LayoutRenderers/AspNetRequestRouteParametersRenderer.cs
  tests/Shared/LayoutRenderers/AspNetRequestRouteParametersRendererTests.cs
Labels: size/L

#742 Version 5.0 Release Candidate 1
  CHANGELOG.MD
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web.AspNetCore/NLogRequestLoggingMiddleware.cs
  src/NLog.Web/NLog.Web.csproj
  src/NLog.Web/NLogRequestLoggingModule.cs
Labels: version, size/M

#744 Version 5.0 Release Candidate 1
  build.ps1
Labels: version, size/XS

#745 Updated xml-docs to no longer recommend NLogBuilder
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
  src/NLog.Web.AspNetCore/NLogBuilder.cs
Labels: docs, size/S

#746 Added Getting-started-with-ASP.NET-Core-6 to readme.txt
  src/NLog.Web.AspNetCore/readme.txt
Labels: docs, size/XS

#747 NLogRequestLogging - Added DurationThresholdMs + ExcludeRequestPaths
  src/NLog.Web.AspNetCore/NLogRequestLoggingMiddleware.cs
  src/NLog.Web.AspNetCore/NLogRequestLoggingOptions.cs
  src/NLog.Web/NLogRequestLoggingModule.cs
  src/Shared/Layouts/W3CExtendedLogField.cs
Labels: feature, size/L
