Repository NLog/NLog.Web, pull requests merged in 2021-02, with the labels that each got.

#627 Updated Net5 example NLog.config to include logging of hosting lifetime messages
  NLog.Web.sln
  examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/ASP.NET Core 2 - VS2017.csproj
  examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Controllers/HomeController.cs
  examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Models/ErrorViewModel.cs
  examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Models/MessageModel.cs
  examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/NLog.config
  examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Program.cs
  examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Startup.cs
  examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Views/Home/Contact.cshtml
  examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Views/Shared/Error.cshtml
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/ASP.NET Core 3 - VS2019.csproj
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Controllers/ApiController.cs
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Controllers/HomeController.cs
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Models/ErrorViewModel.cs
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Models/ItemModel.cs
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/NLog.config
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Program.cs
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Properties/launchSettings.json
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Startup.cs
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Views/Shared/_Layout.cshtml
  examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Views/_ViewImports.cshtml
  examples/ASP.NET Core 5/ASP.NET Core 5 NLog Example/ASP.NET Core 5 NLog Example.csproj
  examples/ASP.NET Core 5/ASP.NET Core 5 NLog Example/Controllers/HomeController.cs
  examples/ASP.NET Core 5/ASP.NET Core 5 NLog Example/Models/ErrorViewModel.cs
  examples/ASP.NET Core 5/ASP.NET Core 5 NLog Example/Program.cs
  examples/ASP.NET Core 5/ASP.NET Core 5 NLog Example/Properties/launchSettings.json
  examples/ASP.NET Core 5/ASP.NET Core 5 NLog Example/Startup.cs
  examples/ASP.NET Core 5/ASP.NET Core 5 NLog Example/Views/Shared/_Layout.cshtml
  examples/ASP.NET Core 5/ASP.NET Core 5 NLog Example/Views/_ViewImports.cshtml
  examples/ASP.NET Core 5/ASP.NET Core 5 NLog Example/nlog.config
Labels: ASP.NET Core 3, example, size/L

#631 AspNetLayoutRendererBase - Added more debug-info when failing to lookup HttpContext
  src/Shared/LayoutRenderers/AspNetLayoutRendererBase.cs
Labels: ASP.NET 4, ASP.NET Core 1, ASP.NET Core 2, ASP.NET Core 3, enhancement, size/S

#634 Remove ThreadAgnostic from AssemblyVersionLayoutRenderer when ASP.NET
  src/Shared/LayoutRenderers/AssemblyVersionLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AssemblyVersionLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/TestInvolvingAspNetHttpContext.cs
Labels: ASP.NET 4, bug, size/M

#635 Fix AssemblyVersionLayoutRenderer on ASP.NET to work with async=true
  src/Shared/LayoutRenderers/AssemblyVersionLayoutRenderer.cs
Labels: bug, size/S

#642 Added SourceLink
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web/NLog.Web.csproj
Labels: size/XS

#643 Remove assembly patching on AppVeyor
  appveyor.yml
Labels: build, size/XS

#639 Enable deterministic build
  build_aspnet.bat
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web/NLog.Web.csproj
Labels: size/S

#644 Added readme.txt for the NuGet packages
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web.AspNetCore/readme.txt
  src/NLog.Web/NLog.Web.csproj
  src/NLog.Web/readme.txt
Labels: docs, size/M

#645 Release 4.11
  CHANGELOG.MD
  appveyor.yml
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: size/M, version
