Repository NLog/NLog.Web, pull requests merged in 2022-12, with the labels that each got.

#897 Code coverage removal
  appveyor.yml
Labels: size/XS

#895 Add ObjectPath to AspNetApplicationValueLayoutRenderer
  appveyor.yml
  src/NLog.Web/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
  tests/NLog.Web.Tests/LayoutRenderers/AspNetApplicationValueLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetItemValueLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetSessionValueLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetSessionValueLayoutRendererTests2.cs
Labels: feature, size/L

#901 Improve code-coverage by testing AddNLogWeb
  NLog.Web.sln
  tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
Labels: unit-test, size/S

#902 AspNetRequestTlsTokenBindingLayoutRenderer - Improve code-coverage
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTlsTokenBindingLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
Labels: unit-test, size/M

#903 AspNetResponseCookieLayoutRenderer - Reduce code complexity
  src/Shared/LayoutRenderers/AspNetResponseCookieLayoutRenderer.cs
Labels: refactoring, size/M

#904 Introducing Items-property as DefaultParameter for consistency
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTrailersLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetResponseTrailersLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestHeadersLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestRouteParametersRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseCookieLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseHeadersLayoutRenderer.cs
Labels: refactoring, size/L

#905 Bump Microsoft.NET.Test.Sdk from 17.4.0 to 17.4.1
  examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/ASP.NET Core 2 - VS2017.csproj
  tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
  tests/NLog.Web.Tests/NLog.Web.Tests.csproj
Labels: dependencies, size/XS

#906 AspNetLayoutRendererBase - Skip allocating extra HttpContextWrapper
  src/NLog.Web/DefaultHttpContextAccessor.cs
  src/Shared/Internal/HttpContextExtensions.cs
  src/Shared/LayoutRenderers/AspNetLayoutRendererBase.cs
Labels: ASP.NET 4, performance, size/S

#900 ASP.NET buffering wrapper target
  src/NLog.Web.AspNetCore/NLogBufferingTargetWrapperMiddleware.cs
  src/NLog.Web/NLogHttpModule.cs
  src/Shared/Internal/LogEventInfoBuffer.cs
  src/Shared/Targets/Wrappers/AspNetBufferingTargetWrapper.cs
  tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
  tests/NLog.Web.AspNetCore.Tests/NLogBufferingTargetWrapperMiddlewareTests.cs
  tests/NLog.Web.Tests/NLogHttpModuleTests.cs
Labels: feature, size/XXL

#907 AspNetBufferingTargetWrapper - Replaced dictionary with TargetBufferListNode
  src/Shared/Internal/LogEventInfoBuffer.cs
  src/Shared/Targets/Wrappers/AspNetBufferingTargetWrapper.cs
  tests/NLog.Web.AspNetCore.Tests/NLogBufferingTargetWrapperMiddlewareTests.cs
  tests/Shared/FakeHttpContextAccessor.cs
  tests/Shared/LayoutRenderers/AspNetCookieLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetQueryStringLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestFormLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestHeadersLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetResponseCookieLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetResponseHeadersLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetVerboseResponseCookieLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AssemblyVersionLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/TestInvolvingAspNetHttpContext.cs
  tests/Shared/Targets/AspNetBufferingTargetWrapperTests.cs
Labels: performance, size/XL

#908 AspNetBufferingTargetWrapperTests - Added testing of multiple http-contexts
  tests/Shared/Targets/AspNetBufferingTargetWrapperTests.cs
Labels: unit-test, size/M

#909 AspNetBufferingTargetWrapper - Skip HttpContextWrapper allocation
  src/NLog.Web/NLogHttpModule.cs
  src/Shared/Targets/Wrappers/AspNetBufferingTargetWrapper.cs
Labels: performance

#910 AspNetBufferingTargetWrapper - Use NLogHttpModule EventHandler like before
  src/NLog.Web/NLogHttpModule.cs
  src/Shared/Targets/Wrappers/AspNetBufferingTargetWrapper.cs
  tests/Shared/Targets/AspNetBufferingTargetWrapperTests.cs
Labels: size/L

#912 AspNetRequestHeadersLayoutRenderer - Reduce code duplication
  src/Shared/Internal/HttpHeaderCollectionValues.cs
  src/Shared/LayoutRenderers/AspNetRequestHeadersLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseHeadersLayoutRenderer.cs
Labels: refactoring, size/L

#913 AspNetBufferingTargetWrapper - Use NLogHttpModule EventHandler like before
  src/Shared/Targets/Wrappers/AspNetBufferingTargetWrapper.cs
Labels: size/XS

#898 Split README.md file for Web and Web.AspNetCore
  README.md
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web.AspNetCore/README.md
  src/NLog.Web.AspNetCore/readme.txt
  src/NLog.Web/NLog.Web.csproj
  src/NLog.Web/README.md
  src/NLog.Web/readme.txt
Labels: size/L

#915 Version 5.2.1
  CHANGELOG.MD
  build.ps1
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web.AspNetCore/README.md
  src/NLog.Web/NLog.Web.csproj
  src/NLog.Web/README.md
Labels: version, size/M

#916 Version 5.2.1 (changelog)
  CHANGELOG.MD
Labels: size/XS

#917 AspNetQueryStringLayoutRenderer - Added Exclude option
  src/Shared/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetQueryStringLayoutRendererTests.cs
Labels: enhancement, size/M

#918 AspNetRequestFormLayoutRenderer - Added Items-option for consistency
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTrailersLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetResponseTrailersLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestFormLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetRequestFormLayoutRendererTests.cs
Labels: enhancement, size/M
