Repository NLog/NLog.Web, pull requests merged in 2022-06, with the labels that each got.

#785 NLogRequestPostedBodyModule - Enables ${aspnet-request-posted-body}
  src/NLog.Web.AspNetCore/NLogRequestPostedBodyMiddleware.cs
  src/NLog.Web/NLogRequestPostedBodyModule.cs
  src/Shared/LayoutRenderers/AspNetRequestPostedBodyLayoutRenderer.cs
  tests/NLog.Web.Tests/NLogRequestPostedBodyModuleTests.cs
Labels: enhancement, size/L

#784 Eight Additional layout renders for NLog.Web
  src/Shared/LayoutRenderers/AspNetLayoutMultiValueRendererBase.cs
  src/Shared/LayoutRenderers/AspNetRequestClientCertificateLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestIsWebSocketLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestLocalIpLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestLocalPortLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestRemotePortLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestWebSocketRequestedProtocolsLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseContentTypeLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseHeadersLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetRequestClientCertificateRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestIsWebSocketLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestLocalIpRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestLocalPortRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestRemotePortRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestWebSocketRequestedProtocolsLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetResponseContentTypeRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetResponseHeadersLayoutRendererTests.cs
Labels: feature, size/XXL

#786 AspNetRequestIsWebSocketLayoutRenderer - Changed from true / false to 1 / 0
  src/Shared/LayoutRenderers/AspNetRequestIsWebSocketLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetRequestIsWebSocketLayoutRendererTests.cs
Labels: feature, size/S

#787 NLogRequestPostedBodyMiddleware - Only accept AllowContentTypes
  src/NLog.Web.AspNetCore/NLogRequestPostedBodyMiddleware.cs
  src/NLog.Web.AspNetCore/NLogRequestPostedBodyMiddlewareOptions.cs
  src/NLog.Web/NLogRequestPostedBodyModule.cs
  src/Shared/Internal/HttpContextExtensions.cs
  tests/NLog.Web.AspNetCore.Tests/NLogRequestPostedBodyMiddlewareOptionsTests.cs
  tests/NLog.Web.AspNetCore.Tests/NLogRequestPostedBodyMiddlewareTests.cs
  tests/NLog.Web.Tests/NLogRequestPostedBodyModuleTests.cs
Labels: feature, size/L

#790 Release 4.15 - CHANGELOG
  CHANGELOG.MD
Labels: size/XS

#789 ASP.NET Response Cookie Layout Renderer
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/Shared/LayoutRenderers/AspNetResponseCookieLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetResponseCookieLayoutRendererTests.cs
Labels: size/XL

#791 AspNetRequestCookieLayoutRenderer + AspNetResponseCookieLayoutRenderer with better code-reuse
  src/NLog.Web/Internal/HttpCookieCollectionValues.cs
  src/Shared/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseCookieLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetRequestWebSocketRequestedProtocolsLayoutRendererTests.cs
Labels: refactoring, size/L

#792 AspNetUserClaimLayoutRenderer - Now supported for NLog.Web with NET46
  src/Shared/LayoutRenderers/AspNetUserClaimLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetUserClaimLayoutRendererTests.cs
Labels: ASP.NET 4, size/S

#798 AspNetResponseCookieLayoutRenderer - Extracted ObjectSeparator
  src/Shared/LayoutRenderers/AspNetLayoutMultiValueRendererBase.cs
  src/Shared/LayoutRenderers/AspNetResponseCookieLayoutRenderer.cs
Labels: refactoring, size/M

#799 AspNetResponseCookieLayoutRenderer - Improved handling of empty properties with Verbose
  src/Shared/LayoutRenderers/AspNetResponseCookieLayoutRenderer.cs
Labels: feature, refactoring, size/L

#796 Added AspNet-Request-ConnectionId and AspNet-Response-Has-Started
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestConnectionIdLayoutRenderer.cs
  src/Shared/Internal/HttpContextExtensions.cs
  src/Shared/LayoutRenderers/AspNetRequestClientCertificateLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestIsWebSocketLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestLocalIpLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestLocalPortLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestRemotePortLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestWebSocketRequestedProtocolsLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseHasStartedLayoutRenderer.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestConnectionIdLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestClientCertificateRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetResponseHasStartedLayoutRendererTests.cs
Labels: size/L

#801 Improve unit-test code-coverage for AspNetRequestContentLength + AspNetRequestContentType
  tests/Shared/LayoutRenderers/AspNetRequestContentLengthLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestContentTypeLayoutRendererTests.cs
Labels: size/L

#806 Fixed MissingMethodException for HostBuilderContext.get_HostingEnvironment()
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
  tests/Shared/LayoutRenderers/TestInvolvingAspNetHttpContext.cs
  tests/Shared/LayoutRenderers/W3CLoggerLayoutTests.cs
Labels: bug, size/M

#808 Bump NLog.Extensions.Logging from 5.0.0 to 5.0.1
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web/NLog.Web.csproj
  tests/Shared/LayoutRenderers/W3CLoggerLayoutTests.cs
Labels: dependencies, size/XS

#809 Reformatted ChangeLog to help dependency update bots
  CHANGELOG.MD
Labels: size/L
