Repository NLog/NLog.Web, pull requests merged in 2022-11, with the labels that each got.

#885 Changed LoadConfigurationFromAppSettings to prioritize current directory
  src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs
Labels: size/S

#886 Bump Microsoft.NET.Test.Sdk from 17.3.2 to 17.4.0
  tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
  tests/NLog.Web.Tests/NLog.Web.Tests.csproj
Labels: size/XS

#887 Changed AspNetAppBasePathLayoutRenderer to prioritize current directory
  src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs
  src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetAppBasePathLayoutRendererTests.cs
Labels: size/M

#888 Changed AspNetAppBasePathLayoutRenderer to prioritize current directory (code layout)
  src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs
Labels: size/S

#891 Skip allocating RouteData when only need to lookup single value
  src/Shared/LayoutRenderers/AspNetMvcActionRenderer.cs
  src/Shared/LayoutRenderers/AspNetMvcControllerRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestRouteParametersRenderer.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestTlsHandshakeLayoutRendererTests.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestTrackingConsentLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetMvcActionRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetMvcControllerRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestRouteParametersRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetSessionIDLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetSessionValueLayoutRendererTests2.cs
  tests/Shared/LayoutRenderers/LayoutRenderersTestBase.cs
Labels: performance, size/L

#892 AspNetRequestRouteParametersRenderer - Reduce code complexity
  src/Shared/LayoutRenderers/AspNetRequestRouteParametersRenderer.cs
Labels: size/M

#890 Add ObjectPath to AspNetItemValueLayoutRenderer
  src/Shared/Internal/PropertyReader.cs
  src/Shared/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetItemValueLayoutRendererTests.cs
Labels: size/L

#889 Apply ArgumentNullException.ThrowIfNull to NLog source-code
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
  src/NLog.Web.AspNetCore/Internal/Guard.cs
  tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
  tests/NLog.Web.AspNetCore.Tests/CallerArgumentExpressionTests.cs
Labels: size/L

#893 Apply Guard.ThrowIfNull to more locations, since better than NRE
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
  src/Shared/Internal/Guard.cs
  tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
Labels: refactoring, size/M

#894 Version 5.2.0
  CHANGELOG.MD
  appveyor.yml
  build.ps1
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web/NLog.Web.csproj
  src/Shared/Internal/PropertyReader.cs
  src/Shared/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetItemValueLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetSessionValueLayoutRendererTests.cs
Labels: version, size/L
