Repository NLog/NLog.Web, pull requests merged in 2022-07, with the labels that each got.

#802 Tls Handshake Layout Render
  src/NLog.Web.AspNetCore/Enums/TlsHandshakeProperty.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetTlsHandshakeLayoutRenderer.cs
  src/Shared/Internal/HttpContextExtensions.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetTlsHandshakeLayoutRendererTests.cs
Labels: feature, size/L

#813 Added ApiTests that also validates LayoutRenderer class-names
  src/NLog.Web.AspNetCore/Enums/TlsHandshakeProperty.cs
  tests/Shared/ApiTests.cs
Labels: test, size/L

#811 Add aspnet-request-servervariable and aspnet-request-item layout renders
  src/Shared/LayoutRenderers/AspNetHttpContextItemLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestServerVariableLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetHttpContextItemLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestServerVariableLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetRequestValueLayoutRendererTests.cs
Labels: size/L

#814 Merged AspNetHttpContextItemLayoutRenderer into AspNetItemValueLayoutRenderer
  src/NLog.Web/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetHttpContextItemLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
  tests/NLog.Web.Tests/LayoutRenderers/AspNetApplicationValueLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetHttpContextItemLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetItemValueLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetSessionValueLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetSessionValueLayoutRendererTests2.cs
Labels: refactoring, size/L

#821 Renamed to aspnet-request-tls-handshake
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTlsHandshakeLayoutRenderer.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestTlsHandshakeLayoutRendererTests.cs
Labels: refactoring, size/S

#822 Updated deprecated dependencies
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/ASP.NET 4.6.1 - VS2017.csproj
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/Scripts/jquery.validate.unobtrusive.js
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/Scripts/jquery.validate.unobtrusive.min.js
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/Web.config
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config
  tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
  tests/NLog.Web.Tests/NLog.Web.Tests.csproj
Labels: test, dependencies, size/L

#815 Renderers from HttpContext Features Collection
  src/NLog.Web.AspNetCore/Enums/ByteArrayFormatProperty.cs
  src/NLog.Web.AspNetCore/Enums/TlsTokenBindingProperty.cs
  src/NLog.Web.AspNetCore/Enums/TrackingConsentProperty.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestBidirectionalStreamLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestHttpTransportTypeLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestInherentKeepAliveLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTlsTokenBindingLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTrackingConsentLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTrailersLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetResponseHttpsCompressionLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetResponseTrailersLayoutRenderer.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestBidirectionalStreamLayoutRendererTests.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestHttpTransportTypeLayoutRendererTests.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestInherentKeepAliveLayoutRendererTests.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestTlsTokenBindingLayoutRendererTests.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestTrackingConsentLayoutRendererTests.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestTrailersLayoutRendererTests.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetResponseHttpsCompressionLayoutRendererTests.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetResponseTrailersLayoutRendererTests.cs
Labels: feature, size/XXL

#823 Update AspNetLayoutRendererBase XML docs for DoAppend and use inheritdoc
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestBidirectionalStreamLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestConnectionIdLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestHttpTransportTypeLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestInherentKeepAliveLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTlsHandshakeLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTlsTokenBindingLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTrackingConsentLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTrailersLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetResponseHttpsCompressionLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetResponseTrailersLayoutRenderer.cs
  src/NLog.Web/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetLayoutRendererBase.cs
  src/Shared/LayoutRenderers/AspNetMvcActionRenderer.cs
  src/Shared/LayoutRenderers/AspNetMvcControllerRenderer.cs
  src/Shared/LayoutRenderers/AspNetMvcLayoutRendererBase.cs
  src/Shared/LayoutRenderers/AspNetRequestClientCertificateLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestContentLength.cs
  src/Shared/LayoutRenderers/AspNetRequestContentTypeLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestDurationLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestFormLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestHeadersLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestHostLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestHttpMethodRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestIsWebSocketLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestLocalIpLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestLocalPortLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestPostedBodyLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestReferrerRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestRemotePortLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestRouteParametersRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestServerVariableLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestUrlRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestUserAgent.cs
  src/Shared/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestWebSocketRequestedProtocolsLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseContentLength.cs
  src/Shared/LayoutRenderers/AspNetResponseContentTypeLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseCookieLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseHasStartedLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseHeadersLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseStatusCodeRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionIdLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetTraceIdentifierLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetUserAuthTypeLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetUserClaimLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetUserIdentityLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetUserIsAuthenticatedLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetWebRootPathLayoutRenderer.cs
  src/Shared/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
Labels: docs, size/XL

#824 Updated XML docs with seealso link
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestBidirectionalStreamLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestConnectionIdLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestHttpTransportTypeLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestInherentKeepAliveLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTlsHandshakeLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTlsTokenBindingLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTrackingConsentLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestTrailersLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetResponseHttpsCompressionLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetResponseTrailersLayoutRenderer.cs
  src/NLog.Web/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetMvcActionRenderer.cs
  src/Shared/LayoutRenderers/AspNetMvcControllerRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestClientCertificateLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestContentLength.cs
  src/Shared/LayoutRenderers/AspNetRequestContentTypeLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestDurationLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestFormLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestHeadersLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestHostLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestHttpMethodRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestIsWebSocketLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestLocalIpLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestLocalPortLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestPostedBodyLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestReferrerRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestRemotePortLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestRouteParametersRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestServerVariableLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestUrlRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestUserAgent.cs
  src/Shared/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetRequestWebSocketRequestedProtocolsLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseContentLength.cs
  src/Shared/LayoutRenderers/AspNetResponseContentTypeLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseCookieLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseHasStartedLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseHeadersLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetResponseStatusCodeRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionIdLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetTraceIdentifierLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetUserAuthTypeLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetUserClaimLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetUserIdentityLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetUserIsAuthenticatedLayoutRenderer.cs
  src/Shared/LayoutRenderers/AssemblyVersionLayoutRenderer.cs
  src/Shared/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
Labels: docs, size/M

#826 Fixed sonar qube warnings
  src/NLog.Web.AspNetCore/NLogRequestPostedBodyMiddleware.cs
  src/NLog.Web/Internal/HttpCookieCollectionValues.cs
  src/Shared/Internal/HttpContextExtensions.cs
Labels: refactoring, size/L

#827 Fixed sonar qube warnings
  src/Shared/Internal/HttpContextExtensions.cs
Labels: refactoring, size/XS

#828 Reverted default value for ShutdownOnDispose to false
  src/NLog.Web.AspNetCore/NLogAspNetCoreOptions.cs
Labels: enhancement, size/XS

#829 Version 5.1.0
  CHANGELOG.MD
  appveyor.yml
  build.ps1
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: version, Minor Version, size/M

#833 NLog.Web 5.1.0 (nit pick)
  CHANGELOG.MD
Labels: docs, size/XS

#834 Updated NET6 example to use EventId instead of EventId_Id
  examples/ASP.NET Core 6/ASP.NET Core 6 NLog Example/nlog.config
Labels: docs, size/XS

#835 Extended ValidateLayoutRendererTypeAlias with namespace validation
  tests/Shared/ApiTests.cs
Labels: test, size/XS

#836 Fixed offset by one in AspNetRequestDurationLayoutRenderer
  src/Shared/LayoutRenderers/AspNetRequestDurationLayoutRenderer.cs
Labels: bug, size/XS
