Repository NLog/NLog.Web, pull requests merged in 2022-08, with the labels that each got.

#840 Lowercase key aspnet render
  src/Shared/LayoutRenderers/AspNetLayoutMultiValueRendererBase.cs
  tests/Shared/LayoutRenderers/AspNetQueryStringLayoutRendererTests.cs
Labels: enhancement, size/M

#832 Unit tests and common base class for IHostEnvironment Layout Renderers
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs
  src/NLog.Web/Internal/HostEnvironment.cs
  src/NLog.Web/Internal/IHostEnvironment.cs
  src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs
  src/Shared/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetEnvironmentLayoutRendererTests.cs
  tests/NLog.Web.Tests/FakeHostEnvironment.cs
  tests/Shared/LayoutRenderers/AspNetAppBasePathLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/IISInstanceNameLayoutRendererTests.cs
Labels: test, size/L

#841 AspNetLayoutMultiValueRendererBase - LowerCaseKeys with less allocation
  src/Shared/LayoutRenderers/AspNetLayoutMultiValueRendererBase.cs
Labels: enhancement, size/M

#842 AspNetLayoutMultiValueRendererBase - LowerCaseKeys with less allocation
  src/Shared/LayoutRenderers/AspNetLayoutMultiValueRendererBase.cs
Labels: enhancement, size/S

#843 AspNetWebRootPathLayoutRenderer - Added unit-test
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetWebRootPathLayoutRenderer.cs
  src/Shared/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetWebRootPathLayoutRendererTests.cs
Labels: test, size/L

#844 AspNetWebRootPathLayoutRenderer - Added unit-test with parse and close
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetEnvironmentLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetAppBasePathLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/AspNetWebRootPathLayoutRendererTests.cs
  tests/Shared/LayoutRenderers/IISInstanceNameLayoutRendererTests.cs
Labels: test, size/M

#848 AspNetRequestPostedBodyLayoutRenderer - Single lookup using TryGetValue
  src/Shared/LayoutRenderers/AspNetRequestPostedBodyLayoutRenderer.cs
Labels: performance, size/S

#845 Added layoutrenderer aspnet-request-has-body and aspnet-request-stream-id
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestHasBodyLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestStreamIdLayoutRenderer.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestHasBodyLayoutRendererTests.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestStreamIdLayoutRendererTests.cs
Labels: size/L

#851 Bump Microsoft.NET.Test.Sdk from 17.2.0 to 17.3.0
  tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
  tests/NLog.Web.Tests/NLog.Web.Tests.csproj
Labels: dependencies

#850 Re-Entrancy management for Session Value Layout Render.
  src/Shared/Internal/ReEntrantScopeLock.cs
  src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
Labels: bug, size/L

#853 AspNetSessionValueLayoutRenderer - Skip ReEntrantScopeLock for classic NLog.Web
  src/Shared/Internal/ReEntrantScopeLock.cs
  src/Shared/LayoutRenderers/AspNetSessionIdLayoutRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
Labels: enhancement, size/L

#854 Updated dependency NLog.Extensions.Logging v5.0.2
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web/NLog.Web.csproj
Labels: dependencies, size/XS

#856 aspnet-request-url - change to property-enum instead of booleans
  src/Shared/Enums/AspNetRequestUrlProperty.cs
  src/Shared/LayoutRenderers/AspNetRequestUrlRenderer.cs
  tests/Shared/LayoutRenderers/AspNetRequestUrlRendererTests.cs
Labels: size/L

#852 Version 5.1.1
  CHANGELOG.MD
  build.ps1
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestHasPostedBodyLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestStreamIdLayoutRenderer.cs
  src/NLog.Web.AspNetCore/LayoutRenderers/AspNetResponseHttpsCompressionLayoutRenderer.cs
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web/NLog.Web.csproj
  src/Shared/LayoutRenderers/AspNetRequestUrlRenderer.cs
  src/Shared/LayoutRenderers/AspNetSessionIdLayoutRenderer.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestHasPostedBodyLayoutRendererTests.cs
  tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestStreamIdLayoutRendererTests.cs
  tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
  tests/Shared/LayoutRenderers/AspNetRequestUrlRendererTests.cs
Labels: version, Patch Version, size/L

#858 Updated Microsoft.AspNetCore.Abstractions to match Microsoft.AspNetCore.Http
  README.md
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: size/S

#859 Updated example for ASP.NET Core 6 (Removed UseAuthorization)
  examples/ASP.NET Core 6/ASP.NET Core 6 NLog Example/Program.cs
Labels: size/XS

#860 Bump Microsoft.NET.Test.Sdk from 17.3.0 to 17.3.1
  tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
  tests/NLog.Web.Tests/NLog.Web.Tests.csproj
Labels: dependencies, size/XS

#861 Loading NLog.config from contentRootPath as last fallback
  src/NLog.Web.AspNetCore/AspNetExtensions.cs
  tests/Shared/LayoutRenderers/AspNetRequestUrlRendererTests.cs
Labels: bug, size/M
