Repository NLog/NLog.Web, pull requests merged in 2023-08, with the labels that each got.

#973 Updated XML docs for LoadConfigurationFromAppSettings
  src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs
Labels: docs, size/XS

#974 MIddleware should keep the Task execution context
  src/NLog.Web.AspNetCore/NLogRequestLoggingMiddleware.cs
  src/NLog.Web.AspNetCore/NLogRequestPostedBodyMiddleware.cs
Labels: size/M

#975 Extended AspNetUserClaimLayoutRenderer to handle multi-values
  src/Shared/LayoutRenderers/AspNetUserClaimLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetUserClaimLayoutRendererTests.cs
Labels: feature, size/M

#976 AspNetUserClaimLayoutRenderer - Fixed code smells
  src/Shared/LayoutRenderers/AspNetUserClaimLayoutRenderer.cs
Labels: refactoring, size/S

#978 Updated to latest NLog v5.2.3
  examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
  src/NLog.Web/NLog.Web.csproj
  tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
  tests/NLog.Web.Tests/NLog.Web.Tests.csproj
Labels: dependencies, size/S

#979 Issue 934 and 935, Middleware Initialization Debugging
  src/NLog.Web.AspNetCore/NLogBufferingTargetWrapperMiddleware.cs
  src/NLog.Web.AspNetCore/NLogRequestPostedBodyMiddleware.cs
  src/NLog.Web/NLogHttpModule.cs
  src/NLog.Web/NLogRequestPostedBodyModule.cs
  src/Shared/LayoutRenderers/AspNetRequestPostedBodyLayoutRenderer.cs
  src/Shared/Targets/Wrappers/AspNetBufferingTargetWrapper.cs
Labels: size/M

#980 Better diagnostics when missing HttpModule or MiddleWare - Fixed code smells
  src/Shared/LayoutRenderers/AspNetRequestPostedBodyLayoutRenderer.cs
  src/Shared/Targets/Wrappers/AspNetBufferingTargetWrapper.cs
Labels: size/XS

#981 Version 5.3.3
  CHANGELOG.MD
  build.ps1
  src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Labels: version, size/S
