Repository NLog/NLog.Web, pull requests merged in 2023-01, with the labels that each got.

#919 Updated README.md to remove blank xml-line
  src/NLog.Web.AspNetCore/README.md
  src/NLog.Web/README.md
Labels: enhancement, size/XS

#921 Enable http status code layout renderer to output both the int and En…
  src/Shared/LayoutRenderers/AspNetResponseStatusCodeRenderer.cs
  tests/Shared/LayoutRenderers/AspNetResponseStatusCodeRendererTests.cs
Labels: enhancement, size/L

#922 AspNet Response HttpStatusCode LayoutRenderer as Enum.ToString
  src/Shared/LayoutRenderers/AspNetResponseStatusCodeRenderer.cs
  tests/Shared/LayoutRenderers/AspNetResponseStatusCodeRendererTests.cs
Labels: enhancement, size/M

#923 Handle malformed X-Forwarded-For Header
  src/Shared/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs
  tests/Shared/LayoutRenderers/AspNetRequestIpLayoutRendererTests.cs
Labels: enhancement, size/L
